### ISSUE TITLE
有无训练数据集的链接

### ISSUE THREAD

**Issue by macheng6** [chenjunyi1999/ChatBot-GPT2#1]

**Comment by chenjunyi1999** [comment]
您好，这个项目里面一共有四个数据集。其中三个可以直接用huggingface的datasets库加载，他们的数据和对数据的描述可以在huggingface的文档中查询到，分别是：
https://huggingface.co/datasets/daily_dialog
https://huggingface.co/datasets/empathetic_dialogues
https://huggingface.co/datasets/blended_skill_talk
另外一个是来自：
'https://s3.amazonaws.com/datasets.huggingface.co/personachat/personachat_self_original.json'
希望可以帮到您
